### PR TITLE
fix read stuck on SIM800L

### PR DESCRIPTION
**Pull request by lathoub**
The +CIPRXGET response indicates the amount of bytes that are ready to be read (the 3rd parameter). modemreadassumes that indeed these amout of characters CAN be read. This turns out not to be case. Sometimes stream.readreturns -1before the expected number of characters are read!

remove the wait when no data is available and
when character read return -1 (no more chars to read), quit the routine.

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Hi. Thanks for pointing this out.
I think the solution is a little bit incorrect, so I' currently working on a proper fix.

**Comment by thbl** [comment]
+1

**Comment by mcr-ksh** [comment]
+1

**Comment by SRGDamia1** [comment]
I think some of the most recent changes should fix this.

**Pull request closed without merging**
