### PR TITLE
add GPS functions

### PR DESCRIPTION
**Pull request by brvdg**
Adding some GPS functions for SIM808

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Could we create a separate SIM808 class and subclass from SIM800?
Just to make better context for the function availability...

**Comment by vshymanskyy** [comment]
Also,take a look at this PR: https://github.com/vshymanskyy/TinyGSM/pull/15
This is similar, and provides example - maybe we can merge them...

**Comment by brvdg** [comment]
This idea sounds good.
But at the moment I have no idea how to create a library which use functions from the sim800 lib.
Or should I made a hole new lib which don't use the sim800 lib?

**Comment by brvdg** [comment]
I created separate file for a SIM808 Module. But it's work only wit the version 2. The SIM808 V1 has different AT commands for GPS.

**Comment by vshymanskyy** [comment]
@brvdg Let me invite you to or new TinyGSM developer chat:
https://gitter.im/tinygsm/Developers?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by brvdg** [comment]
closing this and reopen a new one which is based on newer code.

**Pull request closed without merging**
