### PR TITLE
Updates to XBee, etc

### PR DESCRIPTION
**Pull request by SRGDamia1**
- created virtual modem class in "TinyGSMCommon" which all modems inherit - this made it much easier for me to code other libraries dependent on this library
- minor updates to the XBee based on real responses from newest modems
- grabbed Quenctel M95 from Pacman Pereira and Replicade Ltd.
- grabbed Quenctel MC60 from Tamas Dajka
- cleaned up some junk comments that I'd added earlier
- updated examples to have all the models listed

### CODE REVIEW

**Comment by SRGDamia1** [comment]
I'm sorry, there are a lot of "junk" commits in this that are me doing and un-doing the same things.  They should probably be squashed down.

**Comment by vshymanskyy** [comment]
Thanks for a great contribution!

**Comment by SRGDamia1** [comment]
@vshymanskyy Do you mind if I accept this?

**Comment by vshymanskyy** [comment]
@SRGDamia1 no, I definitely don't mind. Sorry I just coudn't find time to review the huge commit you made! ;)
Anyway, don't see any reasons to hold it back, let's move on. I'll do some tests/adjustments after the merge.

**Pull request merged**
