### PR TITLE
SIM808

### PR DESCRIPTION
**Pull request by brvdg**
added GPS functions for SIM808 and functions to read an delete SMS

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Thank you!

**Comment by vshymanskyy** [comment]
I started restructuring everything - this will take some time. Your SMS functions will be removed and integrated later.

**Comment by vshymanskyy** [comment]
Please try this example https://github.com/vshymanskyy/TinyGSM/blob/master/examples/AllFunctions/AllFunctions.ino in master branch

**Comment by brvdg** [comment]
Can you change the GPS part in the AllFunction scetch to something like this.
Because after an boot it takes an while to get an location. 

`#if defined(TINY_GSM_MODEM_SIM808)
  int gps_altitude;
  int gps_view_satellites;
  int gps_used_satellites;
  float gps_latitude, gps_longitude;
  float gps_speed;

  modem.enableGPS();
  DBG("Waiting for GPS position...");
  while ( !modem.getGPS(&gps_latitude, &gps_longitude, &gps_speed, &gps_altitude, &gps_view_satellites, &gps_used_satellites) ) {
     delay(1000);
  }
  DBG("GPS latitude:", gps_latitude);
  DBG("GPS longitude:", gps_longitude);
  DBG("GPS speed:", gps_speed);
  DBG("GPS altitude:", gps_altitude);
  DBG("GPS viewed satellites :", gps_view_satellites);
  DBG("GPS used satellites:", gps_used_satellites);
  
  String gps_raw = modem.getGPSraw();
  modem.disableGPS();
  DBG("GPS raw data:", gps_raw);
#endif`

The test looks good. I didn't test it in my project. Unfortunately there I need the SMS functions.

**Comment by brvdg** [comment]
Can you add in the feature list the "¹ - supported only on some models or firmware revisions".
Only the newer Version of the SIM808 are supported.

**Comment by vshymanskyy** [comment]
Sure

**Comment by vshymanskyy** [comment]
is there any way to distinguish V1 and V2?

**Comment by brvdg** [comment]
SIM808 R14.xx and above works. 

SIM808 R13 use other AT commands...

**Pull request merged**
