### PR TITLE
added GPS Support, incl. a example for wemos

### PR DESCRIPTION
**Pull request by holgerkoch**
Hi,

i own a SIM808 and try to build a car tracker. For this i need some GPS functions and added this to your project.
I'm not really a programmer and it is my first pull request. So please, be patient.

Best regards

Holger Koch

### CODE REVIEW

**Comment by GeorgianBorca** [comment]
If both of them are on software serial this won't work because you need to add the software serial listen() function.

**Comment by holgerkoch** [comment]
I'm not sure, that i understand you.
I use the integrated GPS from the SIM808. Read the NMEA string and calculate the checksum. Thats very important, that the tinygps (and other) GPS library can understand the incoming nmea stream.

**Comment by achillesh** [comment]
We wish to have a getLocation on A7 board

**Comment by vshymanskyy** [comment]
@holgerkoch @GeorgianBorca Let me invite you to or new TinyGSM developer chat:
https://gitter.im/tinygsm/Developers?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by vshymanskyy** [comment]
Please try latest release, it includes some GPS support.

**Pull request closed without merging**
