### PR TITLE
Added support for Sequans Monarch CAT-M1 modem

### PR DESCRIPTION
**Pull request by nootropicdesign**
I have added support for the Sequans Monarch chipset, and have tested with a Nimbelink Skywire module that has this modem chipset. I believe the implementation is complete and am open to any feedback/questions. I have tested with HTTP, HTTPS, MQTT, and MQTTS clients.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
I have one of these sitting around.  I'll try to test it.

**Comment by mattncsu** [comment]
I tried this with the AT_debug sketch and the modem responds with "ERROR" to every message I send at it.
Didn't have any communication until I defined serial as such:
```
  SerialAT.begin(921600,SERIAL_8N1,LTE_RX,LTE_TX);
  pinMode(LTE_RTS, OUTPUT);
  digitalWrite(LTE_RTS, LOW);
```

**Comment by nootropicdesign** [comment]
> I tried this with the AT_debug sketch and the modem responds with "ERROR" to every message I send at it.
> Didn't have any communication until I defined serial as such:
> 
> ```
>   SerialAT.begin(921600,SERIAL_8N1,LTE_RX,LTE_TX);
>   pinMode(LTE_RTS, OUTPUT);
>   digitalWrite(LTE_RTS, LOW);
> ```

What Arduino are you using that supports serial at 921600? I used an Uno and used SoftwareSerial for modem communication at 19200. I had to configure the modem baud with AT+IPR=19200.

**Comment by mattncsu** [comment]
I'm using hardware serial on a FiPy (ESP32). I saw 921k in one of pycom's sketches I think. Maybe the characters aren't being sent correctly,  can't easily tell because it isnt echoing the commands. Will have to pull out logic analyzer and see.

**Comment by nootropicdesign** [comment]
Wow, sounds like the ESP32 supports that high speed. I had to use the much lower speed. All my tests used 19200 over software serial.

**Comment by mattncsu** [comment]
It might be a hardware issue, I reverted back to the micropython firmware and am still having similar communications problems with the modem.

**Comment by SRGDamia1** [comment]
you can turn the echo on with ATE1

**Comment by mattncsu** [comment]
> you can turn the echo on with ATE1

I get ERROR trying ATE, ATE0, ATE1, ATI, etc.  The only thing it seems to respond positively to is AT.

**Comment by SRGDamia1** [comment]
Can you try hooking it right up to your PC instead of via the ESP32?  Does it accept the AT+IPR command?

**Comment by tavdog** [comment]
Is there any example code I can try with an avr-iot-wg board ? It contains a sequans_monarch but I can't figure out out to set the pins.

**Pull request merged**
