### PR TITLE
Remove recursive call to waitResponse() that removes unprocessed data…

### PR DESCRIPTION
**Pull request by FabianInostroza**
… from the serial rx buffer.

This should solve #62, #21 and maybe #4.

For more details please see #62.

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Genious. I'll try it with my setup and merge it in.

**Comment by vshymanskyy** [comment]
@FabianInostroza please join https://gitter.im/tinygsm

**Comment by FabianInostroza** [comment]
Hi, is everything ok?

**Comment by vshymanskyy** [comment]
The fix is incorporated and will be available with next release. Thank you.

**Pull request closed without merging**
