### PR TITLE
TinyGsmClientSequansMonarch.h: use data mode

### PR DESCRIPTION
**Pull request by ffontaine**
Use data mode instead of text mode to be able to send any content such
as raw binary. This will allow us to use TinyGSM with ArduinoBearSSL and
ArduinoMqtt.

It should be noted that for an unclear reason GSM_NL must be set to '\n'
instead of '\r\n' to avoid "CME ERROR: operation not supported" in this
mode with the Monarch GMS01Q.

Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Is this true for all of the Monarch modules?  I had a VZM20Q, but I somehow fried it.

**Comment by ffontaine** [comment]
I only have a single Monarch module so unfortunately I can't tell if this is a "bug" affecting all Monarch modules or only the version that I'm using on GMS01Q. If you want, I could remove this change from this PR. I'll try to find how to update my module or get another one.

**Comment by ffontaine** [comment]
FYI, I was able to update the version of my GMS01Q from 5.2.0.3 to 5.5.1.0 and I can confirm that this "bug" is still present.

**Comment by ffontaine** [comment]
Do you have additional comments or suggestion on this PR?

**Comment by SRGDamia1** [comment]
No, sorry, I just didn't get to it.

**Pull request merged**
